on:
  workflow_dispatch
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Checkout code
        uses: actions/checkout@v2
      - id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: Run
        env:
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
          BQ_DATASET: ${{ secrets.BQ_DATASET }}
        run: go run ./main.go
